FROM almalinux:9
RUN dnf install telnet iputils net-tools bind-utils -y
CMD ["sleep","2500"]

# networking utilities: to debug
# telnet: For testing connectivity to specific ports.
# iputils: Provides ping and arithmetic.
# net-tools: Provides ifconfig and netstat.
# bind-utils: Provides dig and nslookup.
