services:
  catalogue:
      build: ./catalogue
      image: gaddamakhil/catalogue:1.0.0  
      container_name: catalogue
      depends_on:
      - mongodb
  user:
    build: ./user
    image: gaddamakhil/user:1.0.0
    container_name: user
    depends_on:
    - redis   
    - mongodb
  cart:
    build: ./cart
    image: gaddamakhil/cart:1.0.0
    container_name: cart
    depends_on:   
    - redis
    - catalogue
  frontend:
    build: ./frontend
    image: gaddamakhil/frontend:1.0.0
    container_name: frontend
    depends_on:
    - catalogue
    - user
    - cart  
  mongodb:
    build: ./mongodb  
    image: gaddamakhil/mongodb:1.0.0
    container_name: mongodb
  redis:
   image: redis:7.0
   container_name: redis  

networks:
  default:
     # Use a custom driver
    driver: bridge
    name: roboshop
    external: false #if true,you need to create metworl manually
 


